* SYLLABUS COMPLIANCE

Except for changes that substantially affect implementation of the
grading policy, this syllabus is a guide for the course and is subject
to change. In particular, the course schedule on the webpage,
including topics, readings and project assignments, is subject to
change. Any changes will be announced in class through Zulip. Be sure
to check for updates online regularly.


* POLICY ON ACADEMIC INTEGRITY
There are plenty of resources and examples available that you may
consult and understand to incorporate those ideas into your
projects. However, you must ultimately write your programs
yourself. You are actively encouraged to discuss ideas with one
other. However, unless otherwise stated, you may not give code to or
receive code from anyone else. If you are uncertain about the
appropriateness of a particular case, you may ask.

In this course, special attention is given to contract cheating, where
students have work completed on their behalf that is then submitted
for academic credit. All submitted projects will be thoroughly checked
for authenticity/originality with screening software in order to
prevent contract cheating. Please read more information on Contract
cheating from http:// en.wikipedia.org/wiki/Contract_cheating.

Hunter College regards acts of academic dishonesty (e.g., plagiarism,
cheating on examinations, obtaining unfair advantage, and
falsification of records and official documents) as serious offenses
against the values of intellectual honesty. The college is committed
to enforcing the CUNY Policy on Academic Integrity and will pursue
cases of academic dishonesty according to the Hunter College Academic
Integrity Procedures.

* ADA COMPLIANCE

In compliance with the ADA and with Section 504 of the Rehabilitation
Act, Hunter College is committed to ensuring educational access and
accommodations for all its registered students. Hunter College’s
students with disabilities and medical conditions are encouraged to
register with the Office of AccessABILITY for assistance and
accommodation. For information and appointment contact the Office of
AccessABILITY located in Room E1214 or call (212) 772-4857 /or VRS
(646) 755-3129.

* CUNY POLICY ON SEXUAL MISCONDUCT

In compliance with the CUNY Policy on Sexual Misconduct, Hunter
College reaffirms the prohibition of any sexual misconduct, which
includes sexual violence, sexual harassment, and gender-based
harassment retaliation against students, employees, or visitors, as
well as certain intimate relationships. Students who have experienced
any form of sexual violence on or off campus (including CUNY-sponsored
trips and events) are entitled to the rights outlined in the Bill of
Rights for Hunter College.

a. Sexual Violence: Students are strongly encouraged to immediately
   report the incident by calling 911, contacting NYPD Special Victims
   Division Hotline (646-610-7272) or their local police precinct, or
   contacting the College’s Public Safety Office (212-772-4444).

b. All Other Forms of Sexual Misconduct: Students are also encouraged
   to contact the College’s Title IX Campus Coordinator, Dean John
   Rose (jtrose@hunter.cuny.edu or 212-650-3262) or Colleen Barry
   (colleen.barry@hunter.cuny.edu or 212-772-4534) and seek
   complimentary services through the Counseling and Wellness Services
   Office, Hunter East 1123. CUNY Policy on Sexual Misconduct:
   http://www.cuny.edu/about/administration/offices/la/Policy-on-SexualMisconduct-12-1-14-with-links.pdf
