* General instructions for all projects:

** Directory structure

Each project should be placed in a folder in your assignments repo
using the name specified in each assignment. Upper and lower case
letters are considered different so case matters.

** Files to include

Make sure your repo includes all files necessary to compile and run
your project. This should include:

- All necessary .cpp and .h files
- Any data files.
- A Makefile
- A Readme.org file (see below)

Do not include any other files unless specified in the assignment. 

** Readme.org file
The Readme.org file should include any instruction needed to compile
and run your project.


** Makefile and targets

All projects will require a Makefile to control compilation.

All Makefiles will require these targets

- main - to build an executable named main
- clean - to remove .o files

Additionally, some projects will require Doctest based testing. They
should also include a target:
- tests - build the test executable named tests

** Testing

All projects will be compiled and tested under Linux. Your program
will be run using the following command sequence:

#+begin_src bash
  make clean
  make
  ./main
#+end_src

For projects that require Doctest based testing, they will
additionally be run using the sequence:

#+begin_src bash
  make tests
  ./tests

#+end_src

Any deviation from this will be specified in the specific project. 

