* Project 3 Sorts

* Due:4/08 7:00am


* Folder and files

- Create a folder under assignments named *sorts*
  and place all files there.

- This project will be built up as a series of smaller
  assignments. Make sure to complete each part as assigned.

* Part 1 - Due 3/10 before class

** Merge Sort

Copy the sorts.cpp we did in class from the web site (or make sure you
have the equivalent code).

Add to it a routine named ~std::vector<int> msort(std::vector<int> v)~
that performs the mergesort routine that we outlined in class.

Remember the outline is:

1. If the list you're sorting is less than size 2 then just return it.
2. Otherwise
   1. Split the list into two halves (equal if the list is even
      length, and one off if the list odd length). Do this by copying
      each half into a new std::vector
   2. mergesort the two halves
   3. Use the merge we wrote in class to merge the results into a new
      std::vector
   4. return the new std::vector<int>


The signature should be ~std::vector<int> msort(std::vector v)~

** Write another program named mode.cpp 

In this program add the following routines:
1. int count(std::vector<int> v, int value) - this will return the
   number of times value appears in the unsorted vector v.
2. int largest(std::vector<int> v) - this will return the largest
   value in vector v.
3. A main routine that builds a std::vector<int> of random values and
   tests the above routines.
4. int mode(std::vector<int> v)  which returns the mode of std::vector
   v, that is, the item that appears the most frequently. If there are
   more than one mode then just return any of them. That is, if the
   vector contains 1,5,4,6,4,8,6,4,12,6,22 then you could return 4 or
   6 because both appear most frequently - 3 times.

   
* Part 2 - Due  3/15 7:00am

write a new version of qsort called qsort2. It shoulld have the
following signature ~std::vector<int> qsort2(std::vector<int> list,
int low, int high);~.

It should:

1. Use a reasonable pivot (as opposed to just list[0])
2. It should perform the sort *in place*, that is it should
   rearrange the elements in the vector around the pivot as opposed to
   copying to a new vector. It should then return itself.
   
* Part 3 - Due 4/8 7:00am
Modify the version of sorts.cpp that you already have.
1. Write the in-place version. This can be tricky. If you do not succeed in getting all the bugs out, grab a copy from a classmate or online but make sure to crdit your source with a comment. You'll get full credit for this either way so spend some time trying to get it bug free but don't stress if you have to resort to someone elses code for this.,
2. Write code to use a better pivot as we discussed in class.
3. Run some time tests on the both quicksorts using both a good and a bad pivot. Use a variety of data sets. Also run the mergesort on these data sets. Create a file in this folder named results.md or results.org - this is a text file for markdown or org markdown. In it, describe your results - is one better or worse and under what circumstances or doesn't it make a differnce. Just a short summary of what you learned is all you'll need.
